name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build solution
    uses: OxideMod/Actions/.github/workflows/project-build.yml@main
    with:
      branch-postfix: ${{ github.ref_name != 'master' && format('-{0}', github.ref_name) || '' }}
      version-prefix: '2.0'
      project-name: Oxide.Common
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
